// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQBfNhq_00-j53fPQKX9odSavUrdTi31s',
    appId: '1:12433357012:web:85dc355f1202694876e341',
    messagingSenderId: '12433357012',
    projectId: 'zeroo-12c5f',
    authDomain: 'zeroo-12c5f.firebaseapp.com',
    storageBucket: 'zeroo-12c5f.appspot.com',
    measurementId: 'G-W4H2SR8RBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUo8GN-f6JO8CxahdQxf1Ov7_pZ1JF-zM',
    appId: '1:12433357012:android:d138903af7afa7ab76e341',
    messagingSenderId: '12433357012',
    projectId: 'zeroo-12c5f',
    storageBucket: 'zeroo-12c5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABI4lIZ12AvYLW3pALEzJJ5dIRyIFnvrk',
    appId: '1:12433357012:ios:40f1ac94ab8a247676e341',
    messagingSenderId: '12433357012',
    projectId: 'zeroo-12c5f',
    storageBucket: 'zeroo-12c5f.appspot.com',
    iosBundleId: 'com.example.zeroo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABI4lIZ12AvYLW3pALEzJJ5dIRyIFnvrk',
    appId: '1:12433357012:ios:40f1ac94ab8a247676e341',
    messagingSenderId: '12433357012',
    projectId: 'zeroo-12c5f',
    storageBucket: 'zeroo-12c5f.appspot.com',
    iosBundleId: 'com.example.zeroo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQBfNhq_00-j53fPQKX9odSavUrdTi31s',
    appId: '1:12433357012:web:a465c6c50010808d76e341',
    messagingSenderId: '12433357012',
    projectId: 'zeroo-12c5f',
    authDomain: 'zeroo-12c5f.firebaseapp.com',
    storageBucket: 'zeroo-12c5f.appspot.com',
    measurementId: 'G-VKDWQBKLR9',
  );
}
